### ISSUE TITLE
Extension for web app

### ISSUE THREAD

**Issue by afundamental** [ryanpcmcquen/standardnotes_org_mode_editor#10]
Hi,

Like your extension, it helps me focus on my note-taking but when I try to install it to the web app, an error occurs. Would it be possible to resolve this?

**Comment by ryanpcmcquen** [comment]
What's the error?

**Comment by afundamental** [comment]
It says "Error downloading package details. Please check the Extension Link and try again." I used the extension for the web app.

**Comment by ryanpcmcquen** [comment]
Did you try the backup link?

**Comment by afundamental** [comment]
Not sure if I'm doing this right so I entered "https://gitcdn.xyz/repo/ryanpcmcquen/standardnotes_org_mode_editor/gh-pages/org_mode.json" in the Import Extension text box and pressed Enter but nothing is happening. Update: Same error occured

**Comment by ryanpcmcquen** [comment]
Try this:

https://ghcdn.rawgit.org/ryanpcmcquen/standardnotes_org_mode_editor/1.4.8/org_mode.json

**Comment by afundamental** [comment]
Tried and same error so I refreshed the tab and tried again but same error as well, Difference is that error message appeared faster.

**Comment by ryanpcmcquen** [comment]
Probably some kind of CORS issue. Try in a private or incognito with browser extensions disabled.

**Comment by afundamental** [comment]
Tried in both Edge and Chrome, in both normal and incognito for both. Same issue as well.

**Comment by ryanpcmcquen** [comment]
Try this:

https://cdn.jsdelivr.net/gh/ryanpcmcquen/standardnotes_org_mode_editor@1.4.8/org_mode.json

**Comment by afundamental** [comment]
Tried it in both Edge and Chrome but similar error

**Comment by ryanpcmcquen** [comment]
Same error, or similar?

**Comment by ryanpcmcquen** [comment]
Try this:

https://gitcdn.link/cdn/ryanpcmcquen/standardnotes_org_mode_editor/a2e59b7fa98ae80ae26df27f4751f36480c3f101/org_mode.json

**Comment by afundamental** [comment]
> Same error, or similar?

Same issue as before, It got installed now

> Try this:
> 
> https://gitcdn.link/cdn/ryanpcmcquen/standardnotes_org_mode_editor/a2e59b7fa98ae80ae26df27f4751f36480c3f101/org_mode.json

This works now, thank you

**Comment by ryanpcmcquen** [comment]
Thanks for sticking with me, I updated the README.
