### ISSUE TITLE
Folding and new line issue

### ISSUE THREAD

**Issue by afundamental** [ryanpcmcquen/standardnotes_org_mode_editor#11]
Hi,

I got to install your extension (thanks for fixing the link) and I tried it on the web app. 
Two issues occurred:
1. Not sure if I'm doing it correctly but I tried folding via header and via space/indent but the arrow sign does not appear
2. When I press enter and add text, the text returns to the previous line I came from

Can I ask assistance for this?

**Comment by ryanpcmcquen** [comment]
Can you share a video of the behavior? Is this only in the web app and not in the desktop app?

**Comment by afundamental** [comment]
Hello,

How do I send the video?
Edit: Added it here, sorry had to convert it to .mp4 so it can get attached here that's why video is a bit glitchy




https://user-images.githubusercontent.com/92246972/136982792-0a39dca1-c796-4707-81d7-6073946af116.mp4

**Comment by ryanpcmcquen** [comment]
That's the auto paragraph wrapping/formatting. You need newlines in between new paragraphs. Looks like folding is appearing with asterisks as expected.

**Comment by afundamental** [comment]
With asterisk? I didn't see the arrows

**Comment by ryanpcmcquen** [comment]
It will be plus and minus symbols.

**Comment by afundamental** [comment]
I see, this is noted. Thank you for the assistance again
