### ISSUE TITLE
Many changes was done since

### ISSUE THREAD

**Issue by mickael-kerjean** [ryanpcmcquen/standardnotes_org_mode_editor#3]
Hi there, 

Just to let you know I've been doing extensive work on the codemirror org mode mode with numerous bug fixes and a lot more to make it more than just syntax highlight for org documents.

As I'm aware, there's still a bug that appear when you tried to embed several begin/end such as:
```
#+BEGIN_SRC
To quote things in org mode:
#+BEGIN_QUOTE
I'm a quote
#+END_QUOTE
#+END_SRC
```
But it's an hairy edge case I'm not sure how to fix without rewriting the entire thing

**Comment by mickael-kerjean** [comment]
I wrote up a [kinda release note](https://github.com/mickael-kerjean/nuage/wiki/Org-Mode) for the new version, it doesn't mention all the bugfixes but they were quite a few

**Comment by ryanpcmcquen** [comment]
@mickael-kerjean, thank you for letting me know, this looks like a stellar update! Have you considering publishing _Org mode_ as its own separate library (perhaps on `npm`)?

Also, @ansuz will want to update CryptPad's implementation:
https://github.com/xwiki-labs/cryptpad/blob/master/www/code/orgmode.js

**Comment by mickael-kerjean** [comment]
> Have you considering publishing Org mode as its own separate library (perhaps on npm)?

Considering the author of Codemirror didn't want of an org mode mode in the official repo, my moto is: if nobody else is using it, no point to get extra work. I guess you just prove the point I wouldn't be the only user of it so sure why not, I'll look into it

**Comment by ryanpcmcquen** [comment]
@mickael-kerjean, how are you defining this with CodeMirror? It isn't obvious on the new version.

**Comment by mickael-kerjean** [comment]
Thanks for the reminder, I completly forgot this topic

**Comment by ryanpcmcquen** [comment]
@mickael-kerjean, I am now using [`codemirror-orgmode`](https://github.com/mickael-kerjean/codemirror-orgmode)!
