### ISSUE TITLE
emacs key bindings?

### ISSUE THREAD

**Issue by devinaconley** [ryanpcmcquen/standardnotes_org_mode_editor#4]
Thanks for the work on this. Have you explored implementing emacs key bindings?

**Comment by ryanpcmcquen** [comment]
@devinaconley, thanks! I actually had them enabled originally:

https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/commit/353af99d47a296735d51d869f4e65fe5b467a8f6

But they pretty much conflict with every browser shortcut, which makes the experience quite awful. If you have ideas for workarounds I am open to suggestions.

**Comment by devinaconley** [comment]
Ah nice. I wonder if they could be optionally enabled? Would likely be fine to use in the desktop app.

**Comment by ryanpcmcquen** [comment]
@devinaconley ... maybe, I seem to recall collisions with the desktop app as well, but perhaps a simple toggle switch to enable or disable it would not be too much work. I wonder if I can store the setting in `localStorage` ...

**Comment by ryanpcmcquen** [comment]
@devinaconley, I haven't had much time for this but if you put together a PR I would be happy to approve it.

**Comment by ryanpcmcquen** [comment]
@devinaconley, sorry for the very late delivery here, but since this has ran for a while without needing fixes, I just created a separate version with Emacs bindings, the install link is on the README. If you wouldn't mind testing it, I would love feedback.
