### ISSUE TITLE
Text is hidden in dark themes

### ISSUE THREAD

**Issue by JaspalSuri** [ryanpcmcquen/standardnotes_org_mode_editor#5]
Hi!

Thanks for creating and maintaining this editor. I was trying it out because of an issue a user was reporting (that I was unable to reproduce), but discovered another issue where if one uses a dark theme, the text is invisible. 

Are you able to reproduce this issue?

**Comment by ryanpcmcquen** [comment]
I am not using Standard Notes at the moment, but would accept a PR fixing this.

**Comment by JaspalSuri** [comment]
Thanks for letting us know! If you have any feedback for Standard Notes, I'll be more than happy to take note of it (no pun intended). :)

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, ha! The feature I really want is for the attachments not to be stored in Dropbox or Google Drive, I want them with the actual note. The other thing is lack of a web clipper, but I could probably get on without that.

**Comment by JaspalSuri** [comment]
Thanks for the feedback! It's been duly noted. :)

**Comment by John3** [comment]
> 
> @JaspalSuri, ha! The feature I really want is for the attachments not to be stored in Dropbox or Google Drive, I want them with the actual note. The other thing is lack of a web clipper, but I could probably get on without that.

@ryanpcmcquen https://github.com/johnjones4/Standard-Notes-Clipper

Source: [awesome-standard-notes](https://github.com/jonhadfield/awesome-standard-notes/)

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, this will be fixed soon!

**Comment by JaspalSuri** [comment]
That's great to hear! Thank you!

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, does Standard Notes pass the theme data down to editors?

I need some way to determine that I am in a light or dark mode but my iframe doesn't have access to the parent HTML, so I can't just use a standard detection mechanism like I originally thought. If Standard Notes just supplied the external editor with the background color, that would suffice.

**Comment by JaspalSuri** [comment]
According to one of our devs, you should be able to access it:

>The editors have access to all these CSS variables, which include foreground and background color. https://github.com/sn-extensions/StyleKit/blob/master/src/css/main.scss#L2

Here is another list of the same variables: https://docs.standardnotes.org/extensions/themes

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, I need the CSS from JavaScript though ... what permissions do I request for that? The documentation you linked to isn't clear, and I don't see the parent stylesheets in `document.styleSheets`.

**Comment by ryanpcmcquen** [comment]
OK, I found a way to retrieve the theme stylesheet, but I cannot access the `cssRules` because it is a blocked cross origin request (iframe requesting parent stylesheet) ...

```
Uncaught DOMException: CSSStyleSheet.rules getter: Not allowed to access cross-origin stylesheet
```

**Comment by JaspalSuri** [comment]
I can view the text when a dark theme is in use, but not when a  light theme is applied.

**Comment by ryanpcmcquen** [comment]
Yeah, it turns out the theme variables are not available to the JavaScript, and they aren't populating to my stylesheet either.

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, I believe I have resolved all the issues. Since I couldn't figure out a way to access the background color, I added a theme filter chooser in the lower right corner (this lines up nicely with the Standard Notes theme chooser), it persists your setting by using `localStorage`:
![org_mode_theme_filter_chooser_persists](https://user-images.githubusercontent.com/772937/93573368-e353ba00-f94b-11ea-9eaa-34085917f84d.gif)
