### ISSUE TITLE
Global folding or Org files start folded by default

### ISSUE THREAD

**Issue by John-Grebe** [ryanpcmcquen/standardnotes_org_mode_editor#7]
The org-mode editor can be awkward when dealing with large org files that have a lot of headings. It would be easier if there was a way to either easily fold all headings with a button/keyboard shortcut or to simply have all the headers start folded by default like they are in Emacs. As it is a lot easier to access what one is looking for in larger files by unfolding what you want to access instead of scrolling down or folding everything in the way to get to what you want to access.

**Comment by ryanpcmcquen** [comment]
I like the 'folded by default' idea, since that is what Emacs does. Will work on this soon.

**Comment by ryanpcmcquen** [comment]
@John-Grebe, let me know if `1.4.x` solves this for you.

**Comment by John-Grebe** [comment]
> 
> 
> @John-Grebe, let me know if `1.4.x` solves this for you.

Works perfectly as I can now use my large note files in Standard Notes with ease. Thanks for implementing the suggestion, I am amazed by your speed.
