### ISSUE TITLE
Dracula theme not rendering the same colors across clients

### ISSUE THREAD

**Issue by JJGadgets** [ryanpcmcquen/standardnotes_org_mode_editor#8]
I have opened an issue on the Dracula Standard Notes repo, but figured I should link it here too, since it affects the Org Mode editor the most (Markdown Pro didn't have the same issue as far as I can tell)
https://github.com/dracula/standard-notes/issues/7

**Comment by ryanpcmcquen** [comment]
The editor has no way to know the theme. I created upstream issues about this already, but that is why the Org mode editor has a light/dark switch, so it at least can be usable.

**Comment by ryanpcmcquen** [comment]
The Org mode editor is different from most editors in that it changes the color of certain things as well.

**Comment by ryanpcmcquen** [comment]
Related upstream issue:
https://github.com/standardnotes/component-relay/issues/13

**Comment by JJGadgets** [comment]
> why the Org mode editor has a light/dark switch, so it at least can be usable.

Unfortunately, except for Dark Mode on my PopOS install, both modes seem to be incorrect.

Also (I'll open a new issue if needed) the Light/Dark switch's background bar seems to not change colors depending on light/dark. I'd appreciate if it was either adaptive, or just blends into the rest of the chosen Standard Notes theme.

> it changes the color of certain things as well.

Such as? Fast Editor as far as I can tell doesn't do this, for example.

**Comment by ryanpcmcquen** [comment]
Italics and code text are a different color than standard text for example.

**Comment by ryanpcmcquen** [comment]
The switcher bar isn't intended to change. As noted earlier, Standard Notes doesn't expose colors to the editor, so making it 'adaptive' is not possible with Standard Notes as it is today.

**Comment by ryanpcmcquen** [comment]
Nothing to fix until Standard Notes exposes this data, which they don't seem interested in doing.
